title: Robert Spralja
url: "https://ankitsultana.com"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/spralja"
footer_text: "spralja"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "CV"
   link: "cv.pdf"
 - name: "Contact"
   link: "contact"
